name: Validate

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      max-parallel: 8

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -r develop.txt
      - name: Test with pytest
        run: |
          pytest -v
